### ISSUE TITLE
getSignalStrength not working give ever noting back

### ISSUE THREAD

**Issue by sn2k** [Seeed-Studio/GPRS_SIM900#13]
Hello the function getSignalStrength not working give ever 0 back... (and yes i have rssi 18-20 when i direct ask the module)
```
struct WorkStruct
{
    char phone[16];
    char datetime[24];
    char gprsBuffer[64];
    char message[50];
    float temp;
    float hum;
    int oled_modus;
    int signal_level;
} Work;

  bool ok = gsm.getSignalStrength(Work.signal_level);
  Serial.println("QQ"); 
  Serial.println(ok); 
  Serial.println(Work.signal_level); 
```
Thanks for helping

**Comment by lanselambor** [comment]
@sn2k Could you try to type "AT+CSQ" manually in Serial Debug mode? See what you'll get.
What I got as below,
```
OK
AT+CSQ

+CSQ: 23,0
```

**Comment by sn2k** [comment]
Manuali thats functione.... 
But i have a big problem the libory needs too many ram 38% is too much, its not stable...

**Comment by ortegafernando** [comment]
That is why it uses Software Serial and his buffers.
