### ISSUE TITLE
send SMS library return does not work

### ISSUE THREAD

**Issue by javierpelaez** [Seeed-Studio/GPRS_SIM900#14]
Hello,

When I use the sendSMS method it always returns 0, it does not matter if the SMS has been sent correctly or not.

**Comment by zella** [comment]
It may be related with #7. I remember, that the problem was with `DEFAULT_INTERCHAR_TIMEOUT 1500`. I manually change it to bigger value and it becomes worked

**Comment by ortegafernando** [comment]
Change DEFAULT_INTERCHAR_TIMEOUT to 3000 

Check again

**Comment by nexus05** [comment]
Hello

I changed it from 1500 to 3000. No difference. method returns always false.
I also tried 5000 and 10000. Does not work.
