### ISSUE TITLE
signal strength 

### ISSUE THREAD

**Issue by krlogan** [Seeed-Studio/GPRS_SIM900#17]
getSignalStrength(buffer) command is returning  a 0 value despite a return of 15 from the AT+CSQ when manually entered

**Comment by lanselambor** [comment]
Maybe getSignalStrength was invoked before network being registered. Try to wait for network registration.

```C
while(!gprs.isNetworkRegistered())
{
    delay(1000);
    Serial.println("Network has not registered yet!");
}
```
