### ISSUE TITLE
use serial2 mega

### ISSUE THREAD

**Issue by beryindo** [Seeed-Studio/GPRS_SIM900#20]
not work use serial2 in mega2560. any solution ?

**Comment by lanselambor** [comment]
Not all pins on the Mega and Mega 2560 support change interrupts, only the following can be used for RX: 10, 11, 12, 13, 50, 51, 52, 53, 62, 63, 64, 65, 66, 67, 68, 69.

Solution: 
Take down the jumper aim for selecting serial type, by default it connects Rx/Tx with D7/D8, use two jumper wire to connect Rx/Tx with D11/D10.

![001](https://user-images.githubusercontent.com/9337688/33001008-56f32a20-cde6-11e7-9058-5ada305c9bbd.jpg)
