### ISSUE TITLE
Using with SIM800H

### ISSUE THREAD

**Issue by Gianluigi000** [Seeed-Studio/GPRS_SIM900#27]
Hello, just one question: it's possibile to use this library to send/receive sms and to send/receive calls with SIM800H shield?
Many thanks

**Comment by lanselambor** [comment]
@Gianluigi000  This library can be used for both SIM900 and SIM800 shield.

Need to use different power on functionality:
1. For SIM900 shield you have to use powerUpDown().
2. For SIM800L with RST pin, you have to use powerReset().

**Comment by Gianluigi000** [comment]
Ok, Many thanks.
Another question please: the same library can be used with Arduino Zero , not including SoftwareSerial and for example using Arduino Zero Serial or Serial1?
