### ISSUE TITLE
HTTP Post

### ISSUE THREAD

**Issue by lupuandrei** [Seeed-Studio/GPRS_SIM900#34]
This is not an error, it's a question ...
Does anyone have any idea how I could use the library to send a **POST** request with some parameters?

**Comment by lanselambor** [comment]
@lupuandrei With TCP send methd fill the content like this **"POST /media/uploads/mbed_official/hello.txt HTTP/1.0\r\n\r\n"**.

**Comment by chindro** [comment]
The hardware modules SIM800 and SIM900 support HTTP natively. Check the command manual:
http://www.jechavarria.com/wp-content/uploads/2015/05/SIM900-AT-Commands-Manual_V1.07.pdf

I'm currently working on HTTP GET support for this library. If this is done, adding HTTP Post is not a big deal anymore.
