### ISSUE TITLE
sendSms

### ISSUE THREAD

**Issue by Craftplorer** [Seeed-Studio/GPRS_SIM900#37]
Hi,
I noticed that sendSms returns sometimes true even if its get a OK from the sim900 chip (i checked the serial). I tried to increase the timeout from 5 Seconds to 10 and for interchar from 3000 to 6000.It only happens when i send multiple sms. Any guess?

**Comment by lanselambor** [comment]
@Craftplorer I think there are two questions you asking.
1. sendSMS returns true if only "OK" was read, even message was failed sending out. And "OK" may come from other commands.
2. sendSMS may cause timeout by only set 5 seconds and 3 seconds for inter char?

**Comment by lanselambor** [comment]
@Craftplorer Oops, the comment is truly wrong. And sure  it's better to increase the timeout value, I will set it as 20 seconds.

**Comment by Craftplorer** [comment]
@lanselambor Thank you.
