### ISSUE TITLE
readSMS example

### ISSUE THREAD

**Issue by vishal-desai** [Seeed-Studio/GPRS_SIM900#50]
i'm currently working on GSM900A with your library. all the keywords are working well. but example of readSMS is not working. pls help. it's very urgent.

**Comment by HamzaGE** [comment]
There are two methods to read SMS:
  1. GPRS_LoopHandle.ino  -> in order to recieve "+CMTI: "SM"" 
      may be you need to send this command to your shield: "AT+CNMI=2,2,0,0,0"
  2. GPRS_SMSread.ino -> you have to check if there are any 
      UNREAD sms, and you don't need to check serial data continuosly

**Comment by Pillar1989** [comment]
I will close this issue first. If you still need to discuss it, you can open it again.
