### ISSUE TITLE
GPRS_SIM900 won't compile on Seeeduino MEGA.

### ISSUE THREAD

**Issue by nexus05** [Seeed-Studio/GPRS_SIM900#8]
Hello everybody...

Can't compile library on Seeeduino MEGA 
I always get the same error message.
On Seeeduino V.4.2 it works fine....Everything ok.
Anybody knows whats happening here?
It's supposed to work on MEGAs

Error Message:
Arduino: 1.6.6 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\arduino-1.6.6\arduino-builder -dump-prefs -logger=machine -hardware "C:\arduino-1.6.6\hardware" -tools "C:\arduino-1.6.6\tools-builder" -tools "C:\arduino-1.6.6\hardware\tools\avr" -built-in-libraries "C:\arduino-1.6.6\libraries" -libraries "C:\Users\nexus\Documents\Arduino\libraries" -fqbn=arduino:avr:mega:cpu=atmega2560 -ide-version=10606 -build-path "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\Users\nexus\AppData\Local\Temp\arduino_d484ab6bf6d6f33c478d8d4c8bc793bb\sketch_sep21b.ino"
C:\arduino-1.6.6\arduino-builder -compile -logger=machine -hardware "C:\arduino-1.6.6\hardware" -tools "C:\arduino-1.6.6\tools-builder" -tools "C:\arduino-1.6.6\hardware\tools\avr" -built-in-libraries "C:\arduino-1.6.6\libraries" -libraries "C:\Users\nexus\Documents\Arduino\libraries" -fqbn=arduino:avr:mega:cpu=atmega2560 -ide-version=10606 -build-path "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\Users\nexus\AppData\Local\Temp\arduino_d484ab6bf6d6f33c478d8d4c8bc793bb\sketch_sep21b.ino"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "C:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900\GPRS_Shield_Arduino.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "C:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900\sim900.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "C:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino\Suli.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire" "C:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial\SoftwareSerial.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire" "C:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire\Wire.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -M -MG -MP -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire" "C:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire\utility\twi.c"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp"
"C:\arduino-1.6.6\tools-builder\ctags\5.8-arduino2/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\preproc\ctags_target.cpp"
"C:\arduino-1.6.6\tools-builder\ctags\5.8-arduino2/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\preproc\ctags_target.cpp"
"C:\arduino-1.6.6\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10606 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\arduino-1.6.6\hardware\arduino\avr\cores\arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\variants\mega" "-IC:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900" "-IC:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial" "-IC:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire" "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp" -o "C:\Users\nexus\AppData\Local\Temp\buildd484ab6bf6d6f33c478d8d4c8bc793bb.tmp\sketch\sketch_sep21b.ino.cpp.o"
In file included from C:\Users\nexus\AppData\Local\Temp\arduino_d484ab6bf6d6f33c478d8d4c8bc793bb\sketch_sep21b.ino:3:0:

C:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900/GPRS_Shield_Arduino.h:205:7: error: expected unqualified-id before '/' token

      */        

       ^

C:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900/GPRS_Shield_Arduino.h:205:6: error: expected ';' at end of member declaration

      */        

      ^

C:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900/GPRS_Shield_Arduino.h:205:7: error: expected unqualified-id before '/' token

      */        

       ^

Using library GPRS_SIM900 in folder: C:\Users\nexus\Documents\Arduino\libraries\GPRS_SIM900 (legacy)
Using library Suli_Arduino in folder: C:\Users\nexus\Documents\Arduino\libraries\Suli_Arduino (legacy)
Using library SoftwareSerial at version 1.0 in folder: C:\arduino-1.6.6\hardware\arduino\avr\libraries\SoftwareSerial 
Using library Wire at version 1.0 in folder: C:\arduino-1.6.6\hardware\arduino\avr\libraries\Wire 
exit status 1
Error compiling.

**Comment by ortegafernando** [comment]
check it again please, it was a character in line 205.

**Comment by nexus05** [comment]
Thank you.
Problem fixed
